[workspace]
members = ["neuron-engine"]

[package]
name = "GamingTime"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.6"
neuron-engine = { path = "neuron-engine" }
anyhow = "1.0.95"
log = "0.4.25"